# Duration of the experiment each epoch will run for STEPS steps
STEPS: 200 
EPOCHS: 50 
EXPLORE: 2000 
MIN_BUFFER_SIZE_FOR_TRAIN: 4000 
TARGET_UPDATE_STEPS: 1000 

# random seed
ACTION_SEED: 42

# learning rate
INITIAL_LR: 1e-5

INITIAL_BETA : 0.628       # b (1/N)*(1/P)**b   (0-1) and  
BETA_INC : 0.001  # bita inc per sampling  beta goes to 1 after 100 samplings
PER_ALPHA : 0.6 

GAMMA: 0.99
OPTIM: adam
RESUME_TRAINING: False

# EPSILON-GREEDY PARAMETERS
INITIAL_EPSILON: 1
# INITIAL_EPSILON: 0.01 # Turns of exploration (When we want to resume training)
FINAL_EPSILON: 0.01

# BUFFER RELATED
REPLAY_MEMORY: 50000 
BATCH: 32 
BUFFER_NAME: d3qn_gym_test.pickle #For testing
LOAD_BUFFER : True

# Only for the telcoCoreScaling env
MAX_UE_CONNECTED: 250

METRICS_LIST:
  - ue_connected
  - ue_attach_rate
  - cpu_percentage
  - mem_free
  - magma_mme_service
  - vm_count

PROJECT_NAME: test-ICIN-telco-RL-pipeline

BACKUPS_PATH: backups
SAVED_MODELS_PATH: backups/saved_models
SAVED_BUFFER_PATH: backups/replay_buffer
WORKLOAD_LOGS_PATH: backups/workload_gen_logs
TENSORBOARD_ROOT_DIR: backups/tensorboard_runs
TENSORBOARD_RUNS_DIR: backups/tensorboard_runs/d3qn_sine_workload_1